command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: SQL_WAREHOUSE_ID
    value: "b2bb07abff382b79"
  - name: DELTA_TABLE_MERGED
    value: "workspace.default.merged"
  - name: DELTA_TABLE_PREDICTIONS
    value: "workspace.default.predictions_log"
  - name: MODEL_VOLUME_PATH
    value: "/Volumes/workspace/terract/models"
  - name: LAKEHOUSE_ENABLED
    value: "true"
  - name: LOG_PREDICTIONS
    value: "true"
  - name: GENIE_SPACE_ID
    value: "01f11500abac19c7a773ad486d62fbaf"

resources:
  - name: workspace.default.df_final_lightgbm
    description: Historical anomaly detection data (2010-2023)
    permission: READ
  - name: workspace.default.predictions_2024_partial
    description: 2024 prediction-only county-level records
    permission: READ
  - name: workspace.default.stats_2024_pred_summary
    description: 2024 prediction summary statistics
    permission: READ
